### ISSUE TITLE
[question/feature] set can get previous value?

### ISSUE THREAD

**Issue by JoseGalRe** [stackblitz/alien-signals#6]
This library is awesome, and a doubt arose in me.

Can the previous value be returned too in the set method like useState in react?
to avoid calling the get method on a counter as example?

`count.set(count.get() + 1)`
to
`count.set((prev) => prev + 1)`

or this callback can be generate overhead?

**Comment by johnsoncodehk** [comment]
Yes callback can be generate overhead so we may not support this approach, instead you can use the currentValue property:

`count.set(count.currentValue + 1)`

**Comment by jrecinos-applaudo** [comment]
I understand, thanks for the clarification.

**Comment by jrecinos-applaudo** [comment]
I understand, thanks for the clarification.

**Comment by JoseGalRe** [comment]
I understand, thanks for the clarification.
