### ISSUE TITLE
React Binding?

### ISSUE THREAD

**Issue by suchangv** [stackblitz/alien-signals#9]
Thank you for your excellent work. Do you have any plans to provide React Binding APIs or libraries in the future?

It might look like this:

```tsx
import { useSignal, observer } from 'alien-signals'

const App = observer(function App() {
  const count = useSignal(0)
  
  return <button onClick={() => count.set(count.currentValue + 1)}>{count.get()}<button>
})
```

**Comment by suchangv** [comment]
About this, I have a minimal implementation. I know `useState` or `useReducer` might be cause React `tearing`, `useSyncExternalStore` maybe better.

```tsx
import {
  startTrack,
  endTrack,
  Effect,
  setActiveSub,
  activeSub,
  activeTrackId,
  nextTrackId,
  signal,
} from 'alien-signals'
import { useMemo, useState } from 'react'

const useForceUpdate = () => {
  const [_, setState] = useState(0)

  return () => setState((s) => s + 1)
}

export const useSignal = (value) => {
  return useMemo(() => signal(value), [])
}

export function observer(proxyComponent) {
  return new Proxy(proxyComponent, {
    apply(target, thisArg, argArray) {
      const forceUpdate = useForceUpdate()

      const e = useMemo(() => new Effect(forceUpdate), [forceUpdate])

      const prevSub = activeSub
      const prevTrackId = activeTrackId
      setActiveSub(e, nextTrackId())
      startTrack(e)
      try {
        return target.apply(thisArg, argArray)
      } finally {
        setActiveSub(prevSub, prevTrackId)
        endTrack(e)
      }
    },
  })
}

```

**Comment by johnsoncodehk** [comment]
I have no experience with react, so I don't know how the binding layer should work. If you find any limitations on your binding layer with the current implementation, please let me know.

We plan to keep this repo minimal so there will be no binding layer built in, but if you are willing to build a package for binding layer, we can introduce it in the readme.

**Comment by suchangv** [comment]
> I have no experience with react, so I don't know how the binding layer should work. If you find any limitations on your binding layer with the current implementation, please let me know.
> 
> We plan to keep this repo minimal so there will be no binding layer built in, but if you are willing to build a package for binding layer, we can introduce it in the readme.

Thank you for your reply. I will try to build a library for the binding layer.

**Comment by c01nd01r** [comment]
> About this, I have a minimal implementation. I know `useState` or `useReducer` might be cause React `tearing`, `useSyncExternalStore` maybe better.
> 
> ...code...
> 

I'll add my two cents. I think useSignal should also accept a Signal object. This is needed for compatibility with external code that uses alien-signal (like services). It's also useful to pass a signal instance through React Context while maintaining a stable object reference to avoid re-renders.

**Comment by Rajaniraiyn** [comment]
Hey folks dropping it off, https://github.com/Rajaniraiyn/react-alien-signals
